- name: Preparation
  hosts: master1
  tasks:
  - include_role:
       name: prepareation
  - include_role:
       name: etcd-operator
  - include_role:
       name: nats-operator
  - include_role:
       name: coredns-management-api