- name: Copy signed certs to target dir
  copy:
    src: "{{ message_local_tls_certs_dir_path }}/nats"
    dest: "{{ project_template_path }}/"

- name: Copy operator deploy preparation template to target
  template: 
    src: "{{ role_path }}/templates/prepare.yml.j2"
    dest: "{{ project_template_path }}/nats/prepare.yml"
  when: coredns_speaker_mode == "initiative"

- name: Copy operator deploy template to target
  template: 
    src: "{{ role_path }}/templates/operator-deploy.yml.j2"
    dest: "{{ project_template_path }}/nats/operator-deploy.yml"
  when: coredns_speaker_mode == "initiative"

- name: Copy cluster deploy template to target
  template: 
    src: "{{ role_path }}/templates/cluster-deploy.yml.j2"
    dest: "{{ project_template_path }}/nats/cluster-deploy.yml"
  when: coredns_speaker_mode == "initiative"

- name: Remove existing resource for operator
  shell: "{{ oc_binary }} delete -f {{ project_template_path }}/nats/prepare.yml"
  when: coredns_speaker_mode == "initiative"
  ignore_errors: "yes"

- name: Remove older operator
  shell: "{{ oc_binary }} delete -f {{ project_template_path }}/nats/operator-deploy.yml"
  when: coredns_speaker_mode == "initiative"
  ignore_errors: "yes"

- name: Wait 10 secs for deleting older operator-deploy
  pause:
    seconds: 10

- name: Prepare for nats operator
  shell: "{{ oc_binary }} apply -f {{ project_template_path }}/nats/prepare.yml"
  when: coredns_speaker_mode == "initiative"
  ignore_errors: "yes"

- name: Deploy nats operator
  shell: "{{ oc_binary }} apply -f {{ project_template_path }}/nats/operator-deploy.yml"
  when: coredns_speaker_mode == "initiative"
  ignore_errors: "yes"

- name: Remove route tls secret 
  shell: "{{ oc_binary }} delete secret nats-routes-tls -n {{ namespace_coredns_edge }}"
  when: coredns_speaker_mode == "initiative" and nats_use_tls == "yes"
  ignore_errors: "yes"

- name: Rmove server tls secret 
  shell: "{{ oc_binary }} delete secret nats-clients-tls -n {{ namespace_coredns_edge }}"
  when: coredns_speaker_mode == "initiative" and nats_use_tls == "yes"
  ignore_errors: "yes"

- name: Rmove client connection tls  secret 
  shell: "{{ oc_binary }} delete secret nats-client-connection-tls -n {{ namespace_coredns_edge }}"
  when: coredns_speaker_mode == "initiative" and nats_use_tls == "yes"
  ignore_errors: "yes"

- name: Create server tls secret 
  shell: "{{ oc_binary }} create secret generic nats-clients-tls --from-file=ca.pem --from-file=server-key.pem --from-file=server.pem -n {{ namespace_coredns_edge }}"
  args:
    chdir: "{{ project_template_path }}/nats"
  when: coredns_speaker_mode == "initiative" and nats_use_tls == "yes"

- name: Create route tls secret 
  shell: "{{ oc_binary }} create secret generic nats-routes-tls --from-file=ca.pem --from-file=route-key.pem --from-file=route.pem -n {{ namespace_coredns_edge }}"
  args:
    chdir: "{{ project_template_path }}/nats"
  when: coredns_speaker_mode == "initiative" and nats_use_tls == "yes"

- name: Create client connection tls secret 
  shell: "{{ oc_binary }} create secret generic nats-client-connection-tls --from-file=ca.pem --from-file=client-key.pem --from-file=client.pem -n {{ namespace_coredns_edge }}"
  args:
    chdir: "{{ project_template_path }}/nats"
  when: coredns_speaker_mode == "initiative" and nats_use_tls == "yes"

- name: Remove existing cluster
  shell: "{{ oc_binary }} delete -f cluster-deploy.yml"
  args:
    chdir: "{{ project_template_path }}/nats"
  when: coredns_speaker_mode == "initiative"
  ignore_errors: "yes"

- name: Wait 10 secs for deleting existing cluster
  pause:
    seconds: 10

- name: Creating cluster
  shell: "{{ oc_binary }} apply -f cluster-deploy.yml"
  args:
    chdir: "{{ project_template_path }}/nats"
  when: coredns_speaker_mode == "initiative"